MODEL:
  NAME: 'resnet50'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: 'weights/market1501_resnet50_256_128_epoch_120.ckpt'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

TEST:
  ONLY_TEST: True
  
NORMALIZE_WITH_BN: True

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 40

USE_MIXED_PRECISION: True
NORMALIZE_WITH_BN: TRUE
REPRODUCIBLE_NUM_RUNS: 3